export const TOAST_SUCCESS_MESSAGE = "TOAST_SUCCESS_MESSAGE"
export const TOAST_ERROR_MESSAGE = "TOAST_ERROR_MESSAGE"
export const TOAST_WARNING_MESSAGE = "TOAST_WARNING_MESSAGE"
export const TOAST_DISMISS_ALL = "TOAST_DISMISS_ALL"